# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ezstack < Formula
  desc "Manage stacked PRs with git worktrees"
  homepage "https://github.com/KulkarniKaustubh/ezstack"
  version "3.2.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KulkarniKaustubh/ezstack/releases/download/v3.2.5/ezstack_darwin_amd64.tar.gz"
      sha256 "0b625e74d8527e45bc40aa53903bfed9d14bc3d28ac76593b69dfab16a89cf37"

      define_method(:install) do
        bin.install "ezs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KulkarniKaustubh/ezstack/releases/download/v3.2.5/ezstack_darwin_arm64.tar.gz"
      sha256 "2b4034fe4ba7348ff7180cc495222fea985368704e0c40c6616c316b7e86a399"

      define_method(:install) do
        bin.install "ezs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KulkarniKaustubh/ezstack/releases/download/v3.2.5/ezstack_linux_amd64.tar.gz"
      sha256 "7fc8eab2ba3b01b4c4733ba557d9a8c4df87b354e9b3cd1f743a5a2d8ce3ea1c"
      define_method(:install) do
        bin.install "ezs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KulkarniKaustubh/ezstack/releases/download/v3.2.5/ezstack_linux_arm64.tar.gz"
      sha256 "5c67a5f344ef84505248efcac13deb3ec7c794b5a9e2cb6171672c4bee5c4c92"
      define_method(:install) do
        bin.install "ezs"
      end
    end
  end

  def caveats
    <<~EOS
      To enable shell integration (required for cd functionality), add to your shell config:

        eval "$(ezs --shell-init)"
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ezs --version")
  end
end
