# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ezstack < Formula
  desc "Manage stacked PRs with git worktrees"
  homepage "https://github.com/KulkarniKaustubh/ezstack"
  version "4.8.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KulkarniKaustubh/ezstack/releases/download/v4.8.3/ezstack_darwin_amd64.tar.gz"
      sha256 "903481041ea90f3f1aa668e2697b5e1d743a3313cdc8abbd4fcc0ccd831f315c"

      define_method(:install) do
        bin.install "ezs"
        bin.install "ezs-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KulkarniKaustubh/ezstack/releases/download/v4.8.3/ezstack_darwin_arm64.tar.gz"
      sha256 "da76c5b72fc0c0fac6edcf18c9e63712b0c5d7dff860eb084b60cab4425f3bb2"

      define_method(:install) do
        bin.install "ezs"
        bin.install "ezs-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KulkarniKaustubh/ezstack/releases/download/v4.8.3/ezstack_linux_amd64.tar.gz"
      sha256 "e738430ad3f0c975c0a7dc2a5178366f6eb2142b001f4e2158d5a2f900a5aeb8"
      define_method(:install) do
        bin.install "ezs"
        bin.install "ezs-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KulkarniKaustubh/ezstack/releases/download/v4.8.3/ezstack_linux_arm64.tar.gz"
      sha256 "8bbd5f75ca695f77b85f852fad4b76596316df33c723495238440d9d613e9ab0"
      define_method(:install) do
        bin.install "ezs"
        bin.install "ezs-mcp"
      end
    end
  end

  def caveats
    <<~EOS
      To enable shell integration (required for cd functionality), add to your shell config:

        eval "$(ezs --shell-init)"

      To use ezstack from Claude Code, register the MCP server:

        claude mcp add ezstack --scope user -- ezs-mcp
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ezs --version")
  end
end
