# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ezstack < Formula
  desc "Manage stacked PRs with git worktrees"
  homepage "https://github.com/KulkarniKaustubh/ezstack"
  version "4.8.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KulkarniKaustubh/ezstack/releases/download/v4.8.5/ezstack_darwin_amd64.tar.gz"
      sha256 "6166afebff7a8cfe74753f3aa34dee4bad79086bcc6e4f3568e0fc4503074889"

      define_method(:install) do
        bin.install "ezs"
        bin.install "ezs-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KulkarniKaustubh/ezstack/releases/download/v4.8.5/ezstack_darwin_arm64.tar.gz"
      sha256 "d9d9cda9b1a3dbf3afb256fd2bc8bd403d4aa45ebe34523650a61c65b52ecec5"

      define_method(:install) do
        bin.install "ezs"
        bin.install "ezs-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KulkarniKaustubh/ezstack/releases/download/v4.8.5/ezstack_linux_amd64.tar.gz"
      sha256 "121e710835614ad45490f3ba50ad3517eef7bfe518bd2a4773d0185104e497f0"
      define_method(:install) do
        bin.install "ezs"
        bin.install "ezs-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KulkarniKaustubh/ezstack/releases/download/v4.8.5/ezstack_linux_arm64.tar.gz"
      sha256 "e829beeda29740b44603bc69a40af184f4d4c63379ee314eadf901a086929305"
      define_method(:install) do
        bin.install "ezs"
        bin.install "ezs-mcp"
      end
    end
  end

  def caveats
    <<~EOS
      To enable shell integration (required for cd functionality), add to your shell config:

        eval "$(ezs --shell-init)"

      To use ezstack from Claude Code, register the MCP server:

        claude mcp add ezstack --scope user -- ezs-mcp
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ezs --version")
  end
end
