# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ezstack < Formula
  desc "Manage stacked PRs with git worktrees"
  homepage "https://github.com/KulkarniKaustubh/ezstack"
  version "4.8.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KulkarniKaustubh/ezstack/releases/download/v4.8.4/ezstack_darwin_amd64.tar.gz"
      sha256 "ff38bbc2a4c50b354550136ea97c2b60e837781733ef920a786c3e1957d4e996"

      define_method(:install) do
        bin.install "ezs"
        bin.install "ezs-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KulkarniKaustubh/ezstack/releases/download/v4.8.4/ezstack_darwin_arm64.tar.gz"
      sha256 "ffd7a27258baf7c414de15e0a19b382b095b11aea91cc580af7996137213425c"

      define_method(:install) do
        bin.install "ezs"
        bin.install "ezs-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KulkarniKaustubh/ezstack/releases/download/v4.8.4/ezstack_linux_amd64.tar.gz"
      sha256 "82dfa6a301ee034c37a89d022ffa0d1a79fd92f0a1915a455522581bc80d827c"
      define_method(:install) do
        bin.install "ezs"
        bin.install "ezs-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KulkarniKaustubh/ezstack/releases/download/v4.8.4/ezstack_linux_arm64.tar.gz"
      sha256 "9ecca47d1101f622f29edafd22e777cdff724011f18b2574ac81cf23d8b1c65b"
      define_method(:install) do
        bin.install "ezs"
        bin.install "ezs-mcp"
      end
    end
  end

  def caveats
    <<~EOS
      To enable shell integration (required for cd functionality), add to your shell config:

        eval "$(ezs --shell-init)"

      To use ezstack from Claude Code, register the MCP server:

        claude mcp add ezstack --scope user -- ezs-mcp
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ezs --version")
  end
end
